name: CI

on:
  pull_request:
  push:
    branches:
    - portable-python

jobs:
  tests:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macos-latest]
        python-version: [3.8.18, 3.9.18, 3.10.13]
        include:
          - runs-on: macos-latest
            c-compiler: "clang"
            cxx-compiler: "clang++"
            initial-dashboard-cache: "CMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.13"

    name: python-${{ matrix.python-version }}-${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v3

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.13.1
      with:
        cmake-version: 3.13.5

    - name: Build
      run: |
        mkdir -p python-build && mkdir -p python-install
        cd python-build
        cmake -DCMAKE_INSTALL_PREFIX:PATH=${{ github.workspace }}/python-install ..
        make -j10
        make install

    - name: Test
      run: |
        ./python-install/bin/python -m test